Header header
float32 x_offset        # target offset of COM in x direction (forward/backward)
float32 y_offset        # target offset of COM in y direction (lateral)
float32 z_offset        # target height of COM in z direction
float32 yaw_offset       # target yaw angle of COM
float32 pitch_offset     # target pitch angle of COM
float32 roll_offset      # target roll angle of COM
float32 enable_sway_roll     # toggle for roll sway
float32 enable_sway_pitch    # toggle for pitch sway
float32 enable_sway_yaw      # toggle for yaw sway
float32 enable_sway_crouch   # toggle for crouch sway
float32 x_left_offset       # target offset of left arm in x direction
float32 y_left_offset       # target offset of left arm in y direction
float32 z_left_offset       # target offset of left arm in z direction
float32 x_right_offset      # target offset of right arm in x direction
float32 y_right_offset      # target offset of right arm in y direction
float32 z_right_offset      # target offset of right arm in z direction