Header header
float64 z_offset            # target height of COM in z direction
float64 yaw_offset          # target yaw angle of COM
float64 pitch_offset        # target pitch angle of COM
float64 roll_offset         # target roll angle of COM
float64 x_left_offset       # target offset of left arm in x direction
float64 y_left_offset       # target offset of left arm in y direction
float64 z_left_offset       # target offset of left arm in z direction
float64 x_right_offset      # target offset of right arm in x direction
float64 y_right_offset      # target offset of right arm in y direction
float64 z_right_offset      # target offset of right arm in z direction
float64 enable_sway_roll     # toggle for roll sway
float64 enable_sway_pitch    # toggle for pitch sway
float64 enable_sway_yaw      # toggle for yaw sway
float64 enable_sway_crouch   # toggle for crouch sway

